development:
  adapter: postgresql
  encoding: unicode
  database: caribbefeast_dev
  host: localhost
  pool: 5
  username: postgres
  password: mateo525

production:
  adapter: postgresql
  encoding: unicode
  database: caribbefeast_dev
  host: localhost
  pool: 5
  username: postgres
  password: mateo525

test:
  adapter: postgresql
  encoding: unicode
  database: caribbefeast_dev
  host: localhost
  pool: 5
  username: postgres
  password: mateo525